import { FaceShape } from '../types';

export type StyleData = {
  id: string;
  name: string;
  category: string;
  matchScore: number;
  description: string;
  reason: string;
  difficulty: 1 | 2 | 3;
  maintenanceTime: number;
  priceRange: string;
  duration: string;
  careTips: string[];
  tags: string[];
  gender: 'male' | 'female' | 'unisex';
  faceShapes: FaceShape[];
  // 추천 알고리즘용 추가 필드
  hairTypes?: ('straight' | 'wavy' | 'curly')[]; // 적합한 모질
  hairAmounts?: ('thin' | 'medium' | 'thick')[]; // 적합한 모량
  // 얼굴 특징별 보너스 (이 특징이 있으면 더 잘 어울림)
  bestFor?: {
    foreheadWidth?: ('narrow' | 'medium' | 'wide')[];
    jawShape?: ('round' | 'angular' | 'pointed')[];
    lowerFaceLength?: ('short' | 'medium' | 'long')[];
    cheekboneProminence?: ('flat' | 'moderate' | 'prominent')[];
  };
};

export const mockStyles: StyleData[] = [
  // ====== 여성 스타일 ======
  {
    id: 'f_001',
    name: '레이어드 미디엄',
    category: '중단발',
    matchScore: 95,
    description: '자연스러운 레이어드 컷으로 얼굴 라인을 부드럽게 감싸주는 스타일입니다. 볼륨감이 자연스럽게 살아나며, 다양한 스타일링이 가능해요.',
    reason: '얼굴형에 맞는 레이어로 갸름한 느낌을 줄 수 있어요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '80,000 ~ 120,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 브러시로 안쪽으로 말아주세요',
      '볼륨 스프레이를 뿌리 쪽에 사용하면 효과적',
      '주 1회 트리트먼트 추천',
    ],
    tags: ['자연스러운', '여성스러운', '직장인'],
    gender: 'female',
    faceShapes: ['round', 'oval', 'square'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['round', 'angular'],
      lowerFaceLength: ['long'],
      cheekboneProminence: ['prominent'],
    },
  },
  {
    id: 'f_002',
    name: '시스루 뱅 보브컷',
    category: '단발',
    matchScore: 91,
    description: '투명한 앞머리와 턱선을 감싸는 보브컷의 조합. 이마와 얼굴 비율을 조절해주며 세련된 느낌을 줍니다.',
    reason: '시스루 뱅이 이마를 자연스럽게 커버해줘요',
    difficulty: 2,
    maintenanceTime: 15,
    priceRange: '60,000 ~ 90,000원',
    duration: '1.5~2개월',
    careTips: [
      '앞머리는 매직기로 살짝 다려주세요',
      '볼륨이 죽지 않도록 엎어서 드라이',
      '끝부분 C컬은 고데기로 살짝',
    ],
    tags: ['트렌디', '청순한', '데이트'],
    gender: 'female',
    faceShapes: ['oval', 'oblong', 'heart'],
    hairTypes: ['straight'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      foreheadWidth: ['wide'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'f_003',
    name: '웨이브 펌 롱',
    category: '긴머리',
    matchScore: 87,
    description: '부드러운 S컬 웨이브가 자연스럽게 흐르는 롱 스타일. 여성스러우면서도 볼륨감이 풍성해 보이는 효과가 있어요.',
    reason: '웨이브가 볼륨을 만들어 모량이 풍성해 보여요',
    difficulty: 3,
    maintenanceTime: 20,
    priceRange: '120,000 ~ 180,000원',
    duration: '3~4개월',
    careTips: [
      '젖은 머리에 무스를 도포 후 자연건조',
      '디퓨저 사용하면 웨이브 유지에 좋아요',
      '주 2회 헤어팩으로 수분 보충',
    ],
    tags: ['여성스러운', '화려한', '파티'],
    gender: 'female',
    faceShapes: ['oval', 'square', 'oblong'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['angular'],
      cheekboneProminence: ['prominent'],
      foreheadWidth: ['narrow'],
    },
  },
  {
    id: 'f_004',
    name: '허쉬컷',
    category: '중단발',
    matchScore: 93,
    description: '울프컷에서 발전한 스타일로, 상단에 볼륨을 주고 아래로 갈수록 가볍게 떨어지는 레이어드. 개성있으면서도 관리가 편해요.',
    reason: '트렌디하면서도 얼굴형 커버력이 좋아요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '70,000 ~ 100,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 손으로 뿌리를 세워주세요',
      '왁스로 끝부분만 살짝 정리',
      '자연건조해도 예쁜 스타일',
    ],
    tags: ['트렌디', '개성있는', '캐주얼'],
    gender: 'female',
    faceShapes: ['round', 'oval', 'heart'],
    hairTypes: ['straight', 'wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      cheekboneProminence: ['prominent'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'f_005',
    name: '원랭스 롱',
    category: '긴머리',
    matchScore: 85,
    description: '같은 길이로 일자 커팅한 클래식한 롱 스타일. 깔끔하고 단정한 느낌을 주며, 묶었을 때도 예쁜 실루엣이에요.',
    reason: '깔끔한 일자 라인이 세련된 느낌을 줘요',
    difficulty: 1,
    maintenanceTime: 10,
    priceRange: '40,000 ~ 60,000원',
    duration: '2~3개월',
    careTips: [
      '브러싱을 자주 해서 엉킴 방지',
      '트리트먼트로 끝부분 관리',
      '자기 전 느슨하게 묶어서 자면 좋아요',
    ],
    tags: ['클래식', '단정한', '직장인'],
    gender: 'female',
    faceShapes: ['oval', 'heart', 'oblong'],
    hairTypes: ['straight'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium'],
      jawShape: ['pointed'],
    },
  },
  {
    id: 'f_006',
    name: 'C컬 단발 펌',
    category: '단발',
    matchScore: 89,
    description: '끝부분만 안쪽으로 말리는 자연스러운 C컬 펌. 얼굴을 감싸는 라인이 부드러운 인상을 만들어줘요.',
    reason: 'C컬이 턱선을 감싸서 얼굴이 작아 보여요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '80,000 ~ 110,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 둥근 브러시로 안쪽으로 말기',
      '고데기로 간단히 리터치 가능',
      '볼륨 스프레이 뿌리 쪽에 사용',
    ],
    tags: ['자연스러운', '청순한', '데일리'],
    gender: 'female',
    faceShapes: ['round', 'square', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      jawShape: ['round', 'angular'],
      lowerFaceLength: ['long', 'medium'],
    },
  },
  {
    id: 'f_007',
    name: '히메컷',
    category: '긴머리',
    matchScore: 82,
    description: '앞머리와 사이드를 짧게 자르고 뒷머리는 긴 독특한 스타일. 동양적이면서도 개성있는 느낌을 줘요.',
    reason: '독특한 프레임이 얼굴형을 잡아줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '60,000 ~ 80,000원',
    duration: '1.5~2개월',
    careTips: [
      '앞머리와 사이드 주기적으로 다듬기',
      '매직기로 사이드 라인 정리',
      '뒷머리는 자연건조 OK',
    ],
    tags: ['개성있는', '동양적', 'Y2K'],
    gender: 'female',
    faceShapes: ['oval', 'oblong', 'heart'],
    hairTypes: ['straight'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['wide'],
      cheekboneProminence: ['prominent'],
    },
  },
  {
    id: 'f_008',
    name: '태슬컷',
    category: '단발',
    matchScore: 88,
    description: '끝부분을 잘게 쳐서 가벼운 느낌을 주는 단발. 태슬(술) 같은 모양이라 태슬컷이라 불려요. 움직일 때 자연스러운 움직임이 매력.',
    reason: '가벼운 끝처리가 얼굴에 부드러운 느낌을 줘요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '50,000 ~ 70,000원',
    duration: '1.5~2개월',
    careTips: [
      '자연건조만으로도 스타일 유지',
      '오일로 끝부분 윤기 살리기',
      '텍스처 스프레이로 움직임 강조',
    ],
    tags: ['자연스러운', '가벼운', '캐주얼'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'square'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      jawShape: ['round'],
      foreheadWidth: ['medium'],
    },
  },

  // ====== 남성 스타일 ======
  {
    id: 'm_001',
    name: '투블럭 댄디컷',
    category: '숏컷',
    matchScore: 93,
    description: '옆과 뒤는 짧게, 윗머리는 볼륨감 있게 올리는 깔끔한 남성 스타일. 직장인부터 학생까지 누구에게나 어울려요.',
    reason: '깔끔한 실루엣이 얼굴형을 정돈해줘요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '15,000 ~ 25,000원',
    duration: '1~1.5개월',
    careTips: [
      '왁스로 앞머리를 올려주세요',
      '사이드는 3주마다 다듬기 추천',
      '매트한 왁스가 자연스러워요',
    ],
    tags: ['깔끔한', '직장인', '데일리'],
    gender: 'male',
    faceShapes: ['round', 'oval', 'square'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium'],
      jawShape: ['angular', 'round'],
    },
  },
  {
    id: 'm_002',
    name: '텍스처 펌',
    category: '미디엄',
    matchScore: 89,
    description: '자연스러운 움직임을 주는 남성 펌 스타일. 손으로 쓸어올리기만 해도 스타일링이 완성되는 편리한 헤어입니다.',
    reason: '자연스러운 볼륨으로 세련된 느낌을 줘요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '40,000 ~ 60,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 후 왁스를 살짝 발라주세요',
      '손으로 비벼가며 자연스럽게 스타일링',
      '너무 많은 제품은 오히려 역효과',
    ],
    tags: ['자연스러운', '트렌디', '캐주얼'],
    gender: 'male',
    faceShapes: ['oval', 'square', 'oblong'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium', 'thick'],
    bestFor: {
      jawShape: ['angular'],
      cheekboneProminence: ['prominent'],
    },
  },
  {
    id: 'm_003',
    name: '리프컷',
    category: '미디엄',
    matchScore: 91,
    description: '나뭇잎처럼 자연스럽게 떨어지는 앞머리가 특징. 이마를 적당히 가려주면서 부드러운 인상을 만들어줘요.',
    reason: '앞머리가 이마를 커버해서 비율이 좋아 보여요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '15,000 ~ 25,000원',
    duration: '1~1.5개월',
    careTips: [
      '앞머리는 드라이 시 좌우로 나눠 말리기',
      '가벼운 왁스로 끝부분만 정리',
      '3주마다 앞머리 다듬기 추천',
    ],
    tags: ['자연스러운', '부드러운', '학생'],
    gender: 'male',
    faceShapes: ['round', 'oval', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      foreheadWidth: ['wide'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'm_004',
    name: '쉐도우 펌',
    category: '미디엄',
    matchScore: 86,
    description: '뿌리 부분에 볼륨을 주는 펌으로, 납작한 머리에 생기를 더해줍니다. 자연스러운 볼륨이 오래 유지돼요.',
    reason: '뿌리 볼륨으로 머리가 풍성해 보여요',
    difficulty: 1,
    maintenanceTime: 3,
    priceRange: '40,000 ~ 60,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 머리를 들어올리며 말리기',
      '스타일링 없이도 볼륨 유지',
      '세팅 스프레이로 지속력 UP',
    ],
    tags: ['볼륨', '편한', '데일리'],
    gender: 'male',
    faceShapes: ['oval', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      foreheadWidth: ['narrow'],
      cheekboneProminence: ['flat'],
    },
  },
  {
    id: 'm_005',
    name: '포마드 슬릭백',
    category: '숏컷',
    matchScore: 84,
    description: '머리를 뒤로 넘겨 깔끔하게 정리하는 클래식한 스타일. 정장과 잘 어울리며 포멀한 자리에 딱이에요.',
    reason: '이마를 드러내서 시원하고 깔끔한 인상이에요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '15,000 ~ 25,000원',
    duration: '1~1.5개월',
    careTips: [
      '포마드를 손에 고르게 편 후 뒤로 빗기',
      '빗을 사용하면 더 깔끔한 마무리',
      '글로시한 포마드 추천',
    ],
    tags: ['클래식', '포멀', '직장인'],
    gender: 'male',
    faceShapes: ['oval', 'oblong', 'square'],
    hairTypes: ['straight'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium'],
    },
  },
  {
    id: 'm_006',
    name: '가일컷',
    category: '숏컷',
    matchScore: 90,
    description: '옆과 뒤를 짧게 밀고 윗머리를 한쪽으로 넘기는 스타일. 군인(GI) 스타일에서 유래했지만 세련되게 변형된 현대적 스타일.',
    reason: '짧고 깔끔해서 얼굴형이 잘 드러나요',
    difficulty: 1,
    maintenanceTime: 3,
    priceRange: '15,000 ~ 20,000원',
    duration: '3~4주',
    careTips: [
      '왁스로 옆으로 넘겨주기만 하면 끝',
      '2~3주마다 사이드 정리 필요',
      '매트 왁스가 자연스러워요',
    ],
    tags: ['깔끔한', '남성적', '군인'],
    gender: 'male',
    faceShapes: ['oval', 'square', 'oblong'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['angular'],
      foreheadWidth: ['medium', 'wide'],
    },
  },
  {
    id: 'm_007',
    name: '애즈펌',
    category: '미디엄',
    matchScore: 88,
    description: '자연스러운 S컬 웨이브가 특징인 남성 인기 펌. "그냥 이렇게 됐어요" 같은 자연스러운 무드를 만들어줍니다.',
    reason: '웨이브가 부드러운 인상을 만들어줘요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '40,000 ~ 60,000원',
    duration: '2~3개월',
    careTips: [
      '왁스를 손에 비벼서 구겨 넣듯이 스타일링',
      '자연건조하면 더 자연스러운 웨이브',
      '오일 세럼으로 윤기 추가',
    ],
    tags: ['자연스러운', '트렌디', '대학생'],
    gender: 'male',
    faceShapes: ['round', 'oval', 'heart'],
    hairTypes: ['straight', 'wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['angular', 'round'],
      cheekboneProminence: ['prominent'],
    },
  },
  {
    id: 'm_008',
    name: '댄디 가르마',
    category: '미디엄',
    matchScore: 85,
    description: '7:3 또는 8:2로 가르마를 타서 정리하는 단정한 스타일. 면접이나 공식 자리에 적합하면서도 일상에서도 무난해요.',
    reason: '단정한 가르마가 신뢰감 있는 인상을 줘요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '15,000 ~ 20,000원',
    duration: '1~1.5개월',
    careTips: [
      '드라이 시 가르마 방향으로 말리기',
      '왁스로 가르마 라인 잡아주기',
      '헤어스프레이로 가르마 고정',
    ],
    tags: ['단정한', '면접', '직장인'],
    gender: 'male',
    faceShapes: ['oval', 'oblong', 'heart'],
    hairTypes: ['straight'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['medium', 'wide'],
      jawShape: ['round'],
    },
  },

  // ====== 트렌드 스타일 (WAD 미용실 참고) ======
  {
    id: 'f_009',
    name: '세미 허쉬컷',
    category: '중단발',
    matchScore: 94,
    description: '허쉬컷의 볼륨감은 살리되 과하지 않게 다듬은 스타일. 상단 레이어는 가볍게, 하단은 자연스럽게 떨어져 데일리로 딱이에요. 성수·홍대 트렌드 미용실에서 가장 인기 있는 스타일.',
    reason: '과하지 않은 레이어가 자연스러운 볼륨감을 줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '70,000 ~ 100,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 손으로 볼륨을 잡아주세요',
      '왁스 없이 자연건조해도 스타일 유지',
      '한 달 반마다 끝부분 정리 추천',
    ],
    tags: ['트렌디', '자연스러운', '성수감성'],
    gender: 'female',
    faceShapes: ['round', 'oval', 'heart'],
    hairTypes: ['straight', 'wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      cheekboneProminence: ['prominent'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'f_010',
    name: '레이어드 펌',
    category: '중단발',
    matchScore: 90,
    description: '레이어드 컷에 자연스러운 웨이브 펌을 더한 스타일. 움직일 때마다 부드러운 결이 살아나며, 1:1 맞춤 시술로 모질에 맞게 약을 조절해요.',
    reason: '레이어 + 펌 조합으로 풍성하고 부드러운 실루엣',
    difficulty: 2,
    maintenanceTime: 15,
    priceRange: '100,000 ~ 150,000원',
    duration: '3~4개월',
    careTips: [
      '젖은 머리에 에센스 바른 후 디퓨저로 드라이',
      '무스를 사용하면 웨이브가 더 또렷하게',
      '주 2회 헤어팩으로 수분 보충',
    ],
    tags: ['여성스러운', '볼륨', '트렌디'],
    gender: 'female',
    faceShapes: ['oval', 'square', 'oblong'],
    hairTypes: ['wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['angular'],
      foreheadWidth: ['narrow'],
    },
  },
  {
    id: 'f_011',
    name: '히피펌',
    category: '긴머리',
    matchScore: 86,
    description: '70년대 히피 무드에서 영감을 받은 자유분방한 웨이브. 큰 웨이브가 자연스럽게 풀어지며 빈티지한 감성을 줘요. 텍스처로 포인트를 준 부드러운 디자인이 특징.',
    reason: '큰 웨이브가 자유롭고 세련된 느낌을 줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '120,000 ~ 160,000원',
    duration: '3~4개월',
    careTips: [
      '자연건조가 오히려 더 예쁜 스타일',
      '오일 세럼으로 윤기와 질감 살리기',
      '빗질은 굵은 빗으로 가볍게만',
    ],
    tags: ['빈티지', '자유분방', '감성적'],
    gender: 'female',
    faceShapes: ['oval', 'heart', 'oblong'],
    hairTypes: ['wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      cheekboneProminence: ['flat', 'moderate'],
      foreheadWidth: ['narrow'],
    },
  },
  {
    id: 'f_012',
    name: '90s 텍스처 레이어드',
    category: '긴머리',
    matchScore: 83,
    description: '90년대 스타일이 돌아오면서 주목받는 텍스처 레이어드. 인위적이지 않고 부드러운 질감으로 포인트를 준 디자인. 명확한 컬보다 자연스러운 움직임이 핵심.',
    reason: '레트로 감성 + 현대적 질감의 완벽한 조화',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '80,000 ~ 120,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 후 텍스처 스프레이로 마무리',
      '고데기로 중간중간 S컬 넣어주면 더 예뻐요',
      '너무 정돈하지 않는 게 포인트',
    ],
    tags: ['레트로', '90s', '텍스처'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'square'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['round', 'angular'],
      lowerFaceLength: ['medium'],
    },
  },
  {
    id: 'm_009',
    name: '쉐도우 리프컷',
    category: '미디엄',
    matchScore: 92,
    description: '리프컷에 쉐도우 펌을 결합한 스타일. 뿌리 볼륨과 자연스러운 앞머리 라인이 조화를 이루며, 최소한의 스타일링으로 멋을 낼 수 있어요.',
    reason: '뿌리 볼륨 + 리프 앞머리로 비율이 좋아 보여요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '50,000 ~ 70,000원',
    duration: '2~3개월',
    careTips: [
      '드라이만 잘 해도 스타일 완성',
      '앞머리는 드라이 시 좌우로 나눠 말리기',
      '매트 왁스로 끝부분만 살짝',
    ],
    tags: ['자연스러운', '편한', '대학생'],
    gender: 'male',
    faceShapes: ['round', 'oval', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      foreheadWidth: ['wide'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'm_010',
    name: '다운펌 숏',
    category: '숏컷',
    matchScore: 87,
    description: '뜨는 머리를 눌러주는 다운펌 + 깔끔한 숏 커트. 머리가 잘 뜨는 사람에게 특히 추천. 아침마다 눌리지 않는 머리와 싸울 필요가 없어요.',
    reason: '다운펌으로 뜨는 머리 걱정 끝',
    difficulty: 1,
    maintenanceTime: 3,
    priceRange: '35,000 ~ 55,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 위에서 아래로 눌러가며 말리기',
      '스타일링 제품 거의 필요 없음',
      '한 달 반마다 사이드 정리',
    ],
    tags: ['편한', '깔끔한', '실용적'],
    gender: 'male',
    faceShapes: ['oval', 'round', 'square', 'oblong'],
    hairTypes: ['straight', 'wavy', 'curly'],
    hairAmounts: ['thin', 'medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium', 'wide'],
    },
  },

  // ====== 추가 남성 스타일 ======
  {
    id: 'm_011',
    name: '세입레이어',
    category: '미디엄',
    matchScore: 90,
    description: '사이드와 뒷머리를 짧게 깎고 윗머리를 레이어드로 자연스럽게 내린 다운펌 스타일. 깔끔하면서도 볼륨감이 살아있어요.',
    reason: '레이어드 다운펌으로 자연스러운 볼륨감을 줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '50,000 ~ 70,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 손가락으로 볼륨을 잡아주세요',
      '왁스보다 에센스로 자연스럽게 마무리',
      '한 달 반마다 사이드 정리 추천',
    ],
    tags: ['자연스러운', '깔끔한', '데일리'],
    gender: 'male',
    faceShapes: ['round', 'oval', 'oblong', 'square', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'm_012',
    name: '텍스처 컷',
    category: '숏컷',
    matchScore: 88,
    description: '짧은 길이에 텍스처를 살린 남성 숏컷. 관리가 쉽고 어디에나 어울리는 만능 스타일이에요.',
    reason: '짧고 깔끔하면서도 질감이 살아있어요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '20,000 ~ 30,000원',
    duration: '1~1.5개월',
    careTips: [
      '매트 왁스로 질감만 살짝 잡아주세요',
      '3주마다 다듬기 추천',
      '스타일링 없이도 깔끔한 실루엣',
    ],
    tags: ['깔끔한', '실용적', '데일리'],
    gender: 'male',
    faceShapes: ['oval', 'round', 'square', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['round', 'angular'],
      foreheadWidth: ['medium', 'wide'],
    },
  },
  {
    id: 'm_013',
    name: '시스루 댄디',
    category: '미디엄',
    matchScore: 87,
    description: '앞머리를 시스루로 살리고 댄디하게 정돈한 미디움 스타일. 이마를 자연스럽게 가려주면서 부드러운 인상을 줘요.',
    reason: '시스루 앞머리가 이마를 자연스럽게 커버해줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '50,000 ~ 70,000원',
    duration: '1.5~2개월',
    careTips: [
      '앞머리는 매직기로 살짝 다려주세요',
      '왁스로 사이드와 뒷머리 정리',
      '앞머리 3주마다 다듬기 추천',
    ],
    tags: ['댄디', '부드러운', '직장인'],
    gender: 'male',
    faceShapes: ['oval', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium', 'thick'],
    bestFor: {
      foreheadWidth: ['wide'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'm_014',
    name: '텍스처 가일',
    category: '미디엄',
    matchScore: 89,
    description: '사이드를 짧게 정돈하고 윗머리에 자연스러운 텍스처를 더한 스트레이트 펌 스타일. 깔끔하면서도 트렌디한 느낌.',
    reason: '가일컷 + 텍스처로 세련된 느낌을 줘요',
    difficulty: 2,
    maintenanceTime: 8,
    priceRange: '45,000 ~ 65,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 옆으로 넘기며 말리기',
      '가벼운 왁스로 질감 살리기',
      '사이드는 3주마다 정리',
    ],
    tags: ['트렌디', '깔끔한', '대학생'],
    gender: 'male',
    faceShapes: ['oblong', 'heart', 'oval', 'round'],
    hairTypes: ['straight'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      foreheadWidth: ['medium', 'wide'],
      cheekboneProminence: ['prominent'],
    },
  },
  {
    id: 'm_015',
    name: '페링컷',
    category: '미디엄',
    matchScore: 86,
    description: '사이드와 뒷머리를 짧게 자르고 윗머리는 자연스럽게 넘긴 미디움 스타일. 깔끔하면서도 캐주얼한 느낌이에요.',
    reason: '자연스럽게 넘긴 스타일이 부드러운 인상을 줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '35,000 ~ 50,000원',
    duration: '1.5~2개월',
    careTips: [
      '드라이 시 넘기는 방향으로 말리기',
      '왁스로 가볍게 정리',
      '한 달마다 사이드 다듬기 추천',
    ],
    tags: ['캐주얼', '자연스러운', '데일리'],
    gender: 'male',
    faceShapes: ['oval', 'round', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['round'],
      lowerFaceLength: ['medium'],
    },
  },
  {
    id: 'm_016',
    name: '텍스처 아이비리그',
    category: '숏컷',
    matchScore: 85,
    description: '클래식한 아이비리그 스타일에 현대적인 텍스처를 더한 숏컷. 정장에도 캐주얼에도 잘 어울리는 만능 스타일.',
    reason: '클래식 + 모던 텍스처로 세련된 느낌이에요',
    difficulty: 1,
    maintenanceTime: 5,
    priceRange: '18,000 ~ 25,000원',
    duration: '1~1.5개월',
    careTips: [
      '포마드나 왁스로 가볍게 정리',
      '빗으로 옆으로 넘겨주면 깔끔',
      '3주마다 다듬기 추천',
    ],
    tags: ['클래식', '단정한', '직장인'],
    gender: 'male',
    faceShapes: ['oval', 'round', 'square', 'oblong'],
    hairTypes: ['straight'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium'],
      jawShape: ['angular'],
    },
  },
  {
    id: 'm_017',
    name: '빈티지펌',
    category: '미디엄',
    matchScore: 88,
    description: '70년대 감성의 빈티지한 스핀스월로펌 스타일. 자유롭고 개성있는 분위기를 원하는 분에게 추천.',
    reason: '빈티지 웨이브가 개성있는 분위기를 줘요',
    difficulty: 2,
    maintenanceTime: 12,
    priceRange: '60,000 ~ 90,000원',
    duration: '3~4개월',
    careTips: [
      '자연건조가 오히려 더 예쁜 스타일',
      '오일 세럼으로 윤기 살리기',
      '굵은 빗으로 가볍게만 빗어주세요',
    ],
    tags: ['빈티지', '개성있는', '감성적'],
    gender: 'male',
    faceShapes: ['oval', 'round', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      cheekboneProminence: ['flat', 'moderate'],
      foreheadWidth: ['narrow'],
    },
  },
  {
    id: 'm_018',
    name: '세미히피펌',
    category: '미디엄',
    matchScore: 87,
    description: '부드러운 베이비펌으로 볼륨감을 살린 미디움 스타일. 히피펌보다 자연스럽고 부드러운 무드.',
    reason: '부드러운 웨이브로 자연스러운 볼륨감을 줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '55,000 ~ 75,000원',
    duration: '2~3개월',
    careTips: [
      '젖은 머리에 무스를 도포 후 자연건조',
      '디퓨저로 말리면 웨이브가 더 선명하게',
      '오일로 끝부분 관리',
    ],
    tags: ['자연스러운', '볼륨', '트렌디'],
    gender: 'male',
    faceShapes: ['round', 'oblong', 'heart'],
    hairTypes: ['wavy', 'curly'],
    hairAmounts: ['thin', 'medium', 'thick'],
    bestFor: {
      cheekboneProminence: ['flat'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'm_019',
    name: '쉐도우펌',
    category: '미디엄',
    matchScore: 89,
    description: '은은한 그림자처럼 자연스러운 웨이브를 더한 미디움 스타일. 뿌리 볼륨까지 잡아줘서 납작한 머리에 딱이에요.',
    reason: '은은한 웨이브 + 뿌리 볼륨으로 풍성해 보여요',
    difficulty: 1,
    maintenanceTime: 8,
    priceRange: '45,000 ~ 60,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 머리를 들어올리며 말리기',
      '왁스 없이도 스타일 유지 가능',
      '세팅 스프레이로 지속력 UP',
    ],
    tags: ['자연스러운', '볼륨', '편한'],
    gender: 'male',
    faceShapes: ['oval', 'round', 'square', 'oblong'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow'],
      cheekboneProminence: ['flat'],
    },
  },
  {
    id: 'm_020',
    name: '빌리펌',
    category: '미디엄',
    matchScore: 86,
    description: '자연스러운 웨이브로 풍성함을 살린 미디움 스타일. 모량이 적은 분도 풍성해 보이는 효과가 있어요.',
    reason: '웨이브로 풍성함을 더해 모량이 많아 보여요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '50,000 ~ 70,000원',
    duration: '2~3개월',
    careTips: [
      '무스를 사용하면 웨이브가 더 또렷하게',
      '자연건조로 자연스러운 질감 살리기',
      '오일 세럼으로 윤기 추가',
    ],
    tags: ['볼륨', '자연스러운', '캐주얼'],
    gender: 'male',
    faceShapes: ['oblong', 'square', 'heart', 'round', 'oval'],
    hairTypes: ['straight', 'wavy', 'curly'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      cheekboneProminence: ['flat'],
      lowerFaceLength: ['medium'],
    },
  },
  {
    id: 'm_021',
    name: '슬릭텍스처컷',
    category: '미디엄',
    matchScore: 87,
    description: '깔끔하게 넘긴 슬릭 스타일에 텍스처를 더한 댄디한 미디움 컷. 포멀하면서도 트렌디한 느낌.',
    reason: '슬릭 + 텍스처로 댄디하고 세련된 느낌이에요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '40,000 ~ 55,000원',
    duration: '1.5~2개월',
    careTips: [
      '포마드로 뒤로 넘겨주세요',
      '빗으로 정리하면 더 깔끔',
      '세팅 스프레이로 마무리',
    ],
    tags: ['댄디', '세련된', '직장인'],
    gender: 'male',
    faceShapes: ['round', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium'],
      jawShape: ['round'],
    },
  },

  // ====== 추가 여성 스타일 ======
  {
    id: 'f_013',
    name: '텍스처컷',
    category: '중단발',
    matchScore: 89,
    description: '슬릭펌으로 자연스러운 흐름을 살린 미디움 스타일. 움직일 때 자연스러운 결이 살아나며 세련된 분위기를 줘요.',
    reason: '자연스러운 흐름이 세련된 분위기를 줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '70,000 ~ 90,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 후 텍스처 스프레이로 마무리',
      '고데기로 중간중간 결 넣어주면 더 예뻐요',
      '오일로 끝부분 윤기 살리기',
    ],
    tags: ['자연스러운', '세련된', '데일리'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'heart'],
    hairTypes: ['straight'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['round'],
      lowerFaceLength: ['medium'],
    },
  },
  {
    id: 'f_014',
    name: '빈티지펌 미디엄',
    category: '중단발',
    matchScore: 88,
    description: '70년대 감성의 베이비펌으로 빈티지한 무드를 연출. 부드러운 웨이브가 여성스러우면서도 레트로한 느낌.',
    reason: '빈티지 웨이브가 독특하고 여성스러운 분위기를 줘요',
    difficulty: 2,
    maintenanceTime: 12,
    priceRange: '90,000 ~ 120,000원',
    duration: '3~4개월',
    careTips: [
      '자연건조가 오히려 더 예쁜 스타일',
      '오일 세럼으로 윤기와 질감 살리기',
      '굵은 빗으로 가볍게만 빗어주세요',
    ],
    tags: ['빈티지', '여성스러운', '감성적'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      cheekboneProminence: ['flat', 'moderate'],
      foreheadWidth: ['narrow'],
    },
  },
  {
    id: 'f_015',
    name: '리프펌',
    category: '긴머리',
    matchScore: 86,
    description: '초코브라운 컬러의 긴 머리에 웨이브펌과 디지털펌을 믹스한 스타일. 풍성하면서도 자연스러운 볼륨이 매력적.',
    reason: '웨이브 + 디지털펌 믹스로 풍성한 볼륨이 살아나요',
    difficulty: 3,
    maintenanceTime: 15,
    priceRange: '120,000 ~ 160,000원',
    duration: '3~4개월',
    careTips: [
      '젖은 머리에 에센스 바른 후 디퓨저로 드라이',
      '주 2회 헤어팩으로 수분 보충',
      '무스를 사용하면 웨이브가 더 또렷하게',
    ],
    tags: ['볼륨', '여성스러운', '트렌디'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'oblong'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['angular'],
      cheekboneProminence: ['prominent'],
    },
  },
  {
    id: 'f_016',
    name: '슬릭펌',
    category: '긴머리',
    matchScore: 85,
    description: '애쉬카키브라운 컬러의 슬릭펌 긴머리 스타일. 매끈하게 떨어지는 라인이 세련되고 시크한 분위기를 줘요.',
    reason: '매끈한 슬릭 라인이 시크한 분위기를 연출해요',
    difficulty: 2,
    maintenanceTime: 12,
    priceRange: '100,000 ~ 130,000원',
    duration: '3~4개월',
    careTips: [
      '드라이 시 브러시로 매끈하게 펴주세요',
      '오일로 윤기와 부드러움 유지',
      '트리트먼트로 모질 관리 필수',
    ],
    tags: ['시크', '세련된', '직장인'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'heart', 'oblong'],
    hairTypes: ['straight'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      foreheadWidth: ['narrow', 'medium'],
      jawShape: ['pointed'],
    },
  },
  {
    id: 'f_017',
    name: '허쉬펌',
    category: '중단발',
    matchScore: 91,
    description: '볼륨감 있는 허쉬컷에 슬릭펌을 더한 스타일. 상단의 풍성한 볼륨과 하단의 자연스러운 흐름이 조화를 이뤄요.',
    reason: '허쉬컷 + 펌으로 볼륨감과 자연스러움을 동시에',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '75,000 ~ 95,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 손으로 볼륨을 잡아주세요',
      '왁스로 끝부분만 살짝 정리',
      '자연건조해도 예쁜 스타일',
    ],
    tags: ['트렌디', '볼륨', '캐주얼'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      cheekboneProminence: ['prominent'],
      lowerFaceLength: ['long'],
    },
  },
  {
    id: 'f_018',
    name: '하이레이어드컷',
    category: '중단발',
    matchScore: 89,
    description: '오렌지브라운 컬러에 C컬펌을 더한 레이어드 미디움 스타일. 높은 위치의 레이어가 얼굴을 갸름하게 보여줘요.',
    reason: '하이 레이어가 얼굴 라인을 갸름하게 잡아줘요',
    difficulty: 2,
    maintenanceTime: 10,
    priceRange: '85,000 ~ 110,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 둥근 브러시로 안쪽으로 말기',
      '볼륨 스프레이 뿌리 쪽에 사용',
      '고데기로 C컬 리터치 가능',
    ],
    tags: ['여성스러운', '갸름한', '트렌디'],
    gender: 'female',
    faceShapes: ['oblong', 'heart', 'oval'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      lowerFaceLength: ['long'],
      cheekboneProminence: ['prominent'],
    },
  },
  {
    id: 'f_019',
    name: '태슬펌',
    category: '단발',
    matchScore: 87,
    description: '다크브라운 컬러의 똑단발에 매직스트레이트펌을 더한 스타일. 매끈하고 단정한 느낌이 매력적이에요.',
    reason: '매끈한 스트레이트 단발이 단정하고 세련된 느낌',
    difficulty: 1,
    maintenanceTime: 8,
    priceRange: '60,000 ~ 80,000원',
    duration: '2~3개월',
    careTips: [
      '드라이 시 브러시로 매끈하게 펴주세요',
      '오일로 끝부분 윤기 살리기',
      '자기 전 실크 베개 추천',
    ],
    tags: ['단정한', '시크', '직장인'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'oblong', 'heart'],
    hairTypes: ['straight'],
    hairAmounts: ['thin', 'medium'],
    bestFor: {
      jawShape: ['round'],
      foreheadWidth: ['medium'],
    },
  },
  {
    id: 'f_020',
    name: '빈티지 S컬펌',
    category: '중단발',
    matchScore: 87,
    description: '레이어드컷에 S컬펌과 오렌지브라운 컬러를 더한 빈티지 미디움 스타일. 볼륨감과 레트로 무드가 매력.',
    reason: 'S컬 + 레이어가 복고적이면서 여성스러운 느낌이에요',
    difficulty: 2,
    maintenanceTime: 12,
    priceRange: '95,000 ~ 125,000원',
    duration: '3~4개월',
    careTips: [
      '디퓨저로 말리면 컬이 더 선명하게',
      '무스를 사용하면 S컬 유지에 좋아요',
      '주 2회 헤어팩 추천',
    ],
    tags: ['빈티지', '볼륨', '레트로'],
    gender: 'female',
    faceShapes: ['oblong', 'heart', 'oval'],
    hairTypes: ['wavy', 'curly'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      cheekboneProminence: ['flat', 'moderate'],
      foreheadWidth: ['narrow'],
    },
  },
  {
    id: 'f_021',
    name: '샌드펌',
    category: '긴머리',
    matchScore: 86,
    description: '애쉬브라운 컬러의 긴 머리에 레이어드컷과 S컬펌을 더한 스타일. 바람에 흩날리는 듯한 자연스러운 웨이브가 매력.',
    reason: '자연스러운 S컬 웨이브가 부드럽고 여성스러워요',
    difficulty: 2,
    maintenanceTime: 12,
    priceRange: '110,000 ~ 140,000원',
    duration: '3~4개월',
    careTips: [
      '젖은 머리에 에센스 바른 후 자연건조',
      '오일 세럼으로 윤기와 질감 살리기',
      '너무 정돈하지 않는 게 포인트',
    ],
    tags: ['자연스러운', '여성스러운', '감성적'],
    gender: 'female',
    faceShapes: ['oval', 'round', 'oblong', 'heart'],
    hairTypes: ['straight', 'wavy'],
    hairAmounts: ['medium', 'thick'],
    bestFor: {
      jawShape: ['angular'],
      lowerFaceLength: ['long'],
    },
  },
];
